// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {Script, console} from "forge-std/Script.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import {Mondeto} from "../src/Mondeto.sol";

contract DeployScript is Script {
    function run() external {
        address usdt = vm.envAddress("USDT_ADDRESS");
        uint256 initialPrice = vm.envUint("INITIAL_PRICE");
        uint256 minPrice = vm.envUint("MIN_PRICE");

        // Load land mask (and dimensions) from JSON file generated by map/generate_land_mask.py
        string memory json = vm.readFile("map/land_mask.json");
        uint16 width = uint16(vm.parseJsonUint(json, ".width"));
        uint16 height = uint16(vm.parseJsonUint(json, ".height"));
        uint256[] memory landMask = abi.decode(vm.parseJson(json, ".mask"), (uint256[]));

        vm.startBroadcast();

        // Deploy implementation
        Mondeto implementation = new Mondeto(width, height);
        console.log("Implementation deployed at:", address(implementation));

        // Deploy proxy with land mask included in initialization
        bytes memory initData = abi.encodeCall(
            Mondeto.initialize,
            (usdt, initialPrice, minPrice, landMask)
        );
        ERC1967Proxy proxy = new ERC1967Proxy(address(implementation), initData);
        console.log("Proxy deployed at:", address(proxy));

        vm.stopBroadcast();
    }
}
