#!/usr/bin/env python3
"""Export Mondeto ABI + addresses to the frontend as a typed TypeScript module.

Usage:
    uv run python3 script/export-abi.py [--out PATH]

Reads:
    out/Mondeto.sol/Mondeto.json   (forge build output)
    .env                           (PROXY_ADDRESS, USDT_ADDRESS)

Writes:
    ../mondeto-fe/apps/web/src/lib/contract.ts   (default, or --out)
"""

import argparse
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT.parent / "mondeto-fe" / "apps" / "web" / "src" / "lib" / "contract.ts"

# Minimal ERC20 ABI — just what the frontend needs for USDT
USDT_ABI = [
    {
        "type": "function",
        "name": "approve",
        "inputs": [
            {"name": "spender", "type": "address", "internalType": "address"},
            {"name": "amount", "type": "uint256", "internalType": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool", "internalType": "bool"}],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "allowance",
        "inputs": [
            {"name": "owner", "type": "address", "internalType": "address"},
            {"name": "spender", "type": "address", "internalType": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "balanceOf",
        "inputs": [
            {"name": "account", "type": "address", "internalType": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256", "internalType": "uint256"}],
        "stateMutability": "view",
    },
]



def main():
    parser = argparse.ArgumentParser(description="Export Mondeto ABI to TypeScript")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output .ts path")
    args = parser.parse_args()

    # Read Foundry artifact
    artifact_path = ROOT / "out" / "Mondeto.sol" / "Mondeto.json"
    if not artifact_path.exists():
        raise SystemExit(f"Artifact not found: {artifact_path}\nRun `forge build` first.")
    artifact = json.loads(artifact_path.read_text())
    abi = artifact["abi"]

    # Read proxy address from latest Deploy broadcast (transactions[1] is the ERC1967Proxy)
    usdt = os.environ.get("USDT_ADDRESS", "")
    if not usdt:
        raise SystemExit("USDT_ADDRESS environment variable must be set")
    broadcast_glob = sorted((ROOT / "broadcast" / "Deploy.s.sol").glob("*/run-latest.json"))
    if broadcast_glob:
        broadcast = json.loads(broadcast_glob[-1].read_text())
        proxy_txn = next(
            t for t in broadcast["transactions"]
            if t.get("contractName") == "ERC1967Proxy" and t.get("transactionType") == "CREATE"
        )
        proxy = proxy_txn["contractAddress"]
    else:
        proxy = "0x" + "0" * 40

    # Format ABI as indented JSON, then wrap in TS
    abi_json = json.dumps(abi, indent=2)
    usdt_json = json.dumps(USDT_ABI, indent=2)

    ts = f"""\
// Auto-generated by mondeto/script/export-abi.py — do not edit by hand.
// Regenerate: cd ../mondeto && uv run python3 script/export-abi.py

export const MONDETO_ADDRESS = '{proxy}' as const
export const USDT_ADDRESS = '{usdt}' as const

export const MONDETO_ABI = {abi_json} as const

export const USDT_ABI = {usdt_json} as const
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(ts)
    print(f"Wrote {args.out} ({len(abi)} ABI entries, proxy={proxy})")


if __name__ == "__main__":
    main()
