#!/usr/bin/env python3
"""Export Mondeto ABI + addresses to the frontend as a typed TypeScript module.

Usage:
    uv run python3 script/export-abi.py [--out PATH]

Reads:
    out/Mondeto.sol/Mondeto.json   (forge build output)
    .env                           (PROXY_ADDRESS, USDT_ADDRESS)

Writes:
    ../mondeto-fe/apps/web/src/lib/contract.ts   (default, or --out)
"""

import argparse
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT.parent / "mondeto-fe" / "apps" / "web" / "src" / "lib" / "contract.ts"

# Minimal ERC20 ABI — just what the frontend needs for USDT
USDT_ABI = [
    {
        "type": "function",
        "name": "approve",
        "inputs": [
            {"name": "spender", "type": "address", "internalType": "address"},
            {"name": "amount", "type": "uint256", "internalType": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool", "internalType": "bool"}],
        "stateMutability": "nonpayable",
    },
    {
        "type": "function",
        "name": "allowance",
        "inputs": [
            {"name": "owner", "type": "address", "internalType": "address"},
            {"name": "spender", "type": "address", "internalType": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256", "internalType": "uint256"}],
        "stateMutability": "view",
    },
    {
        "type": "function",
        "name": "balanceOf",
        "inputs": [
            {"name": "account", "type": "address", "internalType": "address"},
        ],
        "outputs": [{"name": "", "type": "uint256", "internalType": "uint256"}],
        "stateMutability": "view",
    },
]


def read_env(path: Path) -> dict[str, str]:
    env = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # handle `export KEY=VALUE` and `KEY=VALUE`
        m = re.match(r"^(?:export\s+)?(\w+)=(.+?)(?:\s+#.*)?$", line)
        if m:
            env[m.group(1)] = m.group(2).strip("'\"")
    return env


def main():
    parser = argparse.ArgumentParser(description="Export Mondeto ABI to TypeScript")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output .ts path")
    args = parser.parse_args()

    # Read Foundry artifact
    artifact_path = ROOT / "out" / "Mondeto.sol" / "Mondeto.json"
    if not artifact_path.exists():
        raise SystemExit(f"Artifact not found: {artifact_path}\nRun `forge build` first.")
    artifact = json.loads(artifact_path.read_text())
    abi = artifact["abi"]

    # Read .env for addresses
    env = read_env(ROOT / ".env")
    proxy = env.get("PROXY_ADDRESS", "0x" + "0" * 40)
    usdt = env.get("USDT_ADDRESS", "0x" + "0" * 40)

    # Format ABI as indented JSON, then wrap in TS
    abi_json = json.dumps(abi, indent=2)
    usdt_json = json.dumps(USDT_ABI, indent=2)

    ts = f"""\
// Auto-generated by mondeto/script/export-abi.py — do not edit by hand.
// Regenerate: cd ../mondeto && uv run python3 script/export-abi.py

export const MONDETO_ADDRESS = '{proxy}' as const
export const USDT_ADDRESS = '{usdt}' as const

export const MONDETO_ABI = {abi_json} as const

export const USDT_ABI = {usdt_json} as const
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(ts)
    print(f"Wrote {args.out} ({len(abi)} ABI entries, proxy={proxy})")


if __name__ == "__main__":
    main()
